version: "3.9"
   
services:
  db:
    container_name: myran-perales-db-container
    image: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myran_perales_db
      - POSTGRES_USER=myran_perales_user
      - POSTGRES_PASSWORD=myran_perales_password
    networks:
      - local-network
  backend:
    container_name: myran-perales-backend-container
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back_test_unitaire_myran_perales:/code
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - local-network

networks:
  local-network:
    driver: bridge

