# Generated by Django 3.0.3 on 2022-03-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220303_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rick_and_morty_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
