name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker-compose up -d
    - name: create migrations
      run: docker-compose exec -T backend python3 manage.py makemigrations
    - name: run migrations
      run: docker-compose exec -T backend python3 manage.py migrate
    - name: run tests
      run: docker-compose exec -T backend python3 manage.py test
