name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker-compose up -d
        docker exec -it back_test_unitaire_myran_perales /bin/bash
        python3 manage.py makemigrations
        python3 manage.py migrate
        python3 manage.py test
