name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker-compose up -d
    - name: run tests
      run: |
        docker-compose exec -T myran-perales-backend-container python3 manage.py makemigrations
        docker-compose exec -T myran-perales-backend-container python3 manage.py migrate
        docker-compose exec -T myran-perales-backend-container python3 manage.py test
